package org.hacker.core.config;

import com.jfinal.config.Routes;

import org.hacker.module.movie.controller.MovieController;
import org.hacker.module.movieman.controller.MovieManController;
import org.hacker.module.poster.controller.PosterController;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configRoute(Routes me) {
 *   MappingRoute.mapping(me);
 * }
 * </pre>
 */
public class MappingRoute {

  public static void mapping(Routes me) {
    me.add("/movie", MovieController.class);
    me.add("/movieman", MovieManController.class);
    me.add("/poster", PosterController.class);
  }
  
}
