package org.hacker.core.config;

import com.jfinal.config.Routes;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configRoute(Routes me) {
 *   MappingRoute.mapping(me);
 * }
 * </pre>
 */
public class MyMappingRoute {

  public static void mapping(Routes me) {
    
  }
  
}
